package venda_make;

public enum TipoMaquiagemPele {
    BASE,
    CORRETIVO,
    BLUSH_STICK,
    BLUSH_PO,
    BLUSH_CREMOSO,
    CONTORNO_STICK,
    CONTORNO_PO,
    CONTORNO_CREMOSO,
    BRONZER_STICK,
    BRONZER_PO,
    BRONZER_CREMOSO,
    ILUMINADOR_STICK,
    ILUMINADOR_PO,
    ILUMINADOR_CREMOSO,
    ILUMINADOR_LIQUIDO,
    PO_COMPACTO,
    PO_SOLTO,
    BRUMA_FIXADORA,
    BRUMA_HIDRATANTE,
    BATOM
}
